# Generated by Django 5.2.1 on 2025-06-22 04:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_submitted_at_contactmessage_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Lab Tools', 'Lab Tools'), ('Accessories', 'Accessories'), ('Others', 'Others')], max_length=20)),
                ('condition', models.CharField(choices=[('Like New', 'Like New'), ('Good', 'Good'), ('Used', 'Used')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='item_images/')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
