# Generated by Django 5.2.3 on 2025-07-06 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_review"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("lecture_notes", "Lecture Notes"),
                            ("question_papers", "Question Papers"),
                            ("study_guides", "Study Guides"),
                            ("online_courses", "Online Courses"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        choices=[
                            ("MATH101", "Calculus I"),
                            ("MATH201", "Calculus II"),
                            ("PHYS201", "Physics for Engineers"),
                            ("CS101", "Introduction to Computer Science"),
                            ("CS201", "Data Structures"),
                            ("CHEM301", "Organic Chemistry"),
                            ("HIST101", "World History"),
                            ("BUS202", "Business Management"),
                            ("ENG101", "English Composition"),
                            ("BIO101", "Biology"),
                            ("ECON101", "Microeconomics"),
                            ("PSYCH101", "Introduction to Psychology"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "semester",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                        ],
                        max_length=10,
                    ),
                ),
                ("year", models.IntegerField()),
                ("file", models.FileField(upload_to="academic_resources/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("download_count", models.IntegerField(default=0)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
