# Generated by Django 5.2.3 on 2025-07-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_academicresource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicresource",
            name="year",
        ),
        migrations.AlterField(
            model_name="academicresource",
            name="semester",
            field=models.CharField(
                choices=[
                    ("1-I", "Level - Term: 1 - I"),
                    ("1-II", "Level - Term: 1 - II"),
                    ("2-I", "Level - Term: 2 - I"),
                    ("2-II", "Level - Term: 2 - II"),
                    ("3-I", "Level - Term: 3 - I"),
                    ("3-II", "Level - Term: 3 - II"),
                    ("4-I", "Level - Term: 4 - I"),
                    ("4-II", "Level - Term: 4 - II"),
                ],
                max_length=10,
            ),
        ),
    ]
