# Generated by Django 5.2.3 on 2025-07-06 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_add_department_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicresource",
            name="course",
            field=models.CharField(
                choices=[
                    ("MATH101", "Calculus I"),
                    ("MATH201", "Calculus II"),
                    ("PHYS201", "Physics for Engineers"),
                    ("CS101", "Introduction to Computer Science"),
                    ("CS201", "Data Structures"),
                    ("CHEM301", "Organic Chemistry"),
                    ("HIST101", "World History"),
                    ("BUS202", "Business Management"),
                    ("ENG101", "English Composition"),
                    ("BIO101", "Biology"),
                    ("ECON101", "Microeconomics"),
                    ("PSYCH101", "Introduction to Psychology"),
                    ("MATH102", "Linear Algebra"),
                    ("MATH202", "Differential Equations"),
                    ("MATH302", "Probability and Statistics"),
                    ("MATH402", "Numerical Analysis"),
                    ("MATH112", "Discrete Mathematics"),
                    ("MATH322", "Real Analysis"),
                    ("MATH323", "Complex Analysis"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_card",
                    models.ImageField(blank=True, null=True, upload_to="id_cards/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
