# Generated by Django 5.2.3 on 2025-07-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="university",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
