from django.contrib import admin
from django.urls import path
from django.shortcuts import redirect
from main import views


urlpatterns = [
    # Custom dashboard admin actions FIRST
    path('dashboard/approve-resource/<int:resource_id>/', views.admin_approve_resource, name='dashboard_approve_resource'),
    path('dashboard/reject-resource/<int:resource_id>/', views.admin_reject_resource, name='dashboard_reject_resource'),
    # Custom admin actions FIRST
    path('admin/approve-resource/<int:resource_id>/', views.admin_approve_resource, name='admin_approve_resource'),
    path('admin/reject-resource/<int:resource_id>/', views.admin_reject_resource, name='admin_reject_resource'),
    path('admin/', admin.site.urls),
    path('', views.home_view, name='home'),
    path('signup/', views.signup_view, name='signup'),
    path('verify-otp/', views.verify_otp_view, name='verify_otp'),
    path('resend-otp/', views.resend_otp_view, name='resend_otp'),
    path('login/', views.login_view, name='login'),
    path('feed/', views.feed_view, name='feed'),
    path('logout/', views.logout_view, name='logout'),
    path('about/', views.about_view, name='about'),
    path('post/', views.post_item_view, name='post_item'),
    path('contact/', views.contact_view, name='contact'),
    path('books/', views.books_view, name='books'),
    path('resources/', views.resources_view, name='resources'),
    path('browse/', views.browse_view, name='browse'),
    path('browse/lecture-notes/', views.browse_lecture_notes, name='browse_lecture_notes'),
    path('browse/question-papers/', views.browse_question_papers, name='browse_question_papers'),
    path('browse/study-guides/', views.browse_study_guides, name='browse_study_guides'),
    path('download/<int:resource_id>/', views.download_resource, name='download_resource'),
    path('lab_tools/', views.lab_tools_view, name='lab_tools'),
    path('accessories/', views.accessories_view, name='accessories'),
    path('category/books/', views.category_books, name='category_books'),
    path('category/lab-tools/', views.category_lab_tools, name='category_lab_tools'),
    path('category/accessories/', views.category_accessories, name='category_accessories'),
    path('category/others/', views.category_others, name='category_others'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit-post/<int:post_id>/', views.edit_post, name='edit_post'),
    path('profile/delete-post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('book-item/<int:item_id>/', views.book_item, name='book_item'),
    path('manage-booking/<int:booking_id>/', views.manage_booking, name='manage_booking'),
    path('cancel-booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    path('book-item/<int:item_id>/', views.book_item, name='book_item'),
    path('upload/', views.upload, name='upload'),
    path('search/', views.search_items, name='search_items'),
    path('inbox/', views.inbox_view, name='inbox'),
    path('conversation/<int:user_id>/<int:item_id>/', views.conversation_view, name='conversation'),
    path('conversation/<int:user_id>/', views.conversation_view, name='conversation_general'),
    path('send-message/<int:user_id>/<int:item_id>/', views.send_message_view, name='send_message'),
    path('send-message/<int:user_id>/', views.send_message_view, name='send_message_general'),
    path('mark-read/<int:message_id>/', views.mark_message_read, name='mark_message_read'),
    path('see-reviews/', views.see_reviews, name='see_reviews'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    # Admin action URLs
    path('admin-approve-item/<int:item_id>/', views.admin_approve_item, name='admin_approve_item'),
    path('admin-reject-item/<int:item_id>/', views.admin_reject_item, name='admin_reject_item'),
    path('admin/delete-user/<int:user_id>/', views.admin_delete_user, name='admin_delete_user'),
    path('dashboard/delete-review/<int:review_id>/', views.admin_delete_review, name='admin_delete_review'),
    path('dashboard/delete-message/<int:message_id>/', views.admin_delete_message, name='admin_delete_message'),
    path('admin/manage-bookings/', views.admin_manage_bookings, name='admin_manage_bookings'),
    path('admin-manage-booking/<int:booking_id>/', views.admin_manage_booking, name='admin_manage_booking'),
    path('admin-manage-messages/', views.admin_manage_messages, name='admin_manage_messages'),
    path('admin-bulk-delete-messages/', views.admin_bulk_delete_messages, name='admin_bulk_delete_messages'),
    path('admin-edit-review/<int:review_id>/', views.admin_edit_review, name='admin_edit_review'),
    path('admin-manage-users/', views.admin_manage_users, name='admin_manage_users'),
    path('admin-edit-user/<int:user_id>/', views.admin_edit_user, name='admin_edit_user'),
    path('admin-manage-reviews/', views.admin_manage_reviews, name='admin_manage_reviews'),
    path('admin-manage-items/', views.admin_manage_items, name='admin_manage_items'),
    path('admin-edit-item/<int:item_id>/', views.admin_edit_item, name='admin_edit_item'),
    path('admin-delete-item/<int:item_id>/', views.admin_delete_item, name='admin_delete_item'),
    path('admin/conversation/<int:user1_id>/<int:user2_id>/', views.admin_conversation_view, name='admin_conversation'),
    path('admin/conversation/<int:user1_id>/<int:user2_id>/<int:item_id>/', views.admin_conversation_view, name='admin_conversation_item'),
    path('admin-manage-user-messages/', views.admin_manage_user_messages, name='admin_manage_user_messages'),
    path('admin-delete-user-message/<int:message_id>/', views.admin_delete_user_message, name='admin_delete_user_message'),
    path('admin-manage-resources/', views.admin_manage_resources, name='admin_manage_resources'),
]


